### ISSUE TITLE
Style text 

### ISSUE THREAD

**Issue by AlmogRnD** [gnestor/react-native-statusbar-alert#14]
Is there a way to style the text message?

**Comment by gnestor** [comment]
I just merged https://github.com/gnestor/react-native-statusbar-alert/pull/18 which allows users to provide children elements to `StatusBarAlert`, so you can pass custom `Text` elements with styling. Additionally, you can now pass a `style` prop to `StatusBarAlert` that will be applied to the container `View` and `TouchableOpacity`. Let me know if it works for you 👍
