### ISSUE TITLE
Error using pulse

### ISSUE THREAD

**Issue by DVassilev** [gnestor/react-native-statusbar-alert#4]
Got this error when I tried to use pulse and pressed on it:

```
 Style property 'backgroundColor' is not supported by native animated module
```

Is this library still being maintained @gnestor ?

**Comment by macelii** [comment]
I encountered the same problem and landed here plus:
https://github.com/facebook/react-native/issues/11831

**Comment by DVassilev** [comment]
@macelii I just ended up placing the pulse on the text until there's a solution. What version of RN are you using? I'm on 0.39

**Comment by macelii** [comment]
@DVassilev same here on 0.39

**Comment by gnestor** [comment]
I merged a fix and released 0.1.0. Upgrade and give it a try 👍

**Comment by DVassilev** [comment]
Thanks @gnestor, just saw it. Will try it out.

**Comment by DVassilev** [comment]
@gnestor This did not fix it for me, I still get the error.

**Comment by gnestor** [comment]
Have you cloned this repo and `npm link`ed it into your RN project? Or are you installing it from npm? I haven't cut a new release yet so `npm install`ing it won't include this change.

**Comment by macelii** [comment]
I confirm that this is fixed as shown in facebook/react-native#11831
Thanks @gnestor !

**Comment by DVassilev** [comment]
@gnestor I thought you published it to NPM, didn't try local repo. Will you be publishing it?

**Comment by gnestor** [comment]
Ok, 0.2.0 is published!
