### ISSUE TITLE
Height of not visible statusbar-alert uses default statusbar height

### ISSUE THREAD

**Issue by vdlindenmark** [gnestor/react-native-statusbar-alert#7]
In our app we disabled in iOS the statusbar of the os itself. We like to use you're statusbar-alert, but if we use visible={false}, the statusbar-alert keep uses the height of the statusbar from the os...

**Comment by JulianKingman** [comment]
You can use statusbarHeight, like this:

```javascript
const StatusAlert = props => {
  const visible = !!props.statusAlert;
  return (
    <StatusBarAlert
      visible={visible}
      message={props.statusAlert}
      backgroundColor={props.style.backgroundColor}
      color={props.style.color}
      statusbarHeight={visible ? 20 : 0}
    />
  );
};
```

**Comment by gnestor** [comment]
There was a bug (described in https://github.com/gnestor/react-native-statusbar-alert/pull/19) that was just fixed, so this shouldn't be an issue anymore.
